# Generated by Django 3.0.7 on 2020-07-19 09:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('venues_app', '0002_auto_20200718_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Użytkownik',
                     'verbose_name_plural': 'Użytkownicy'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'verbose_name': 'Lokal', 'verbose_name_plural': 'Lokale'},
        ),
        migrations.AlterField(
            model_name='venue',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(
                2020, 7, 19, 9, 18, 36, 620216, tzinfo=utc), verbose_name='data dodania'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='venues_app.User')),
                ('venue', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='venues_app.Venue')),
            ],
            options={
                'verbose_name': 'Ocena',
                'verbose_name_plural': 'Oceny',
                'unique_together': {('user', 'venue')},
            },
        ),
    ]
