# Generated by Django 3.0.7 on 2020-07-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues_app', '0004_auto_20200719_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktywna'),
        ),
    ]
