# Generated by Django 3.0.7 on 2020-07-19 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venues_app', '0005_venue_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='active',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name='data dodania'),
        ),
    ]
