# Generated by Django 3.0.7 on 2020-07-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues_app', '0013_remove_venue_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=255, verbose_name='adres'),
        ),
    ]
