# Generated by Django 3.0.7 on 2020-07-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues_app', '0015_auto_20200721_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                verbose_name='data dodania'),
        ),
    ]
