# Generated by Django 3.0.7 on 2020-07-21 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venues_app', '0017_auto_20200721_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='created_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name='data dodania'),
        ),
    ]
