# Generated by Django 3.0.7 on 2020-07-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues_app', '0018_auto_20200721_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(
                blank=True,
                default='',
                help_text='Dodaj obrazek o wymiarach 200x200px',
                upload_to='media',
                verbose_name='obraz'),
            preserve_default=False,
        ),
    ]
