# Generated by Django 3.0.7 on 2020-07-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues_app', '0020_venue_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='avg_rating',
        ),
    ]
